//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.27 at 07:29:40 AM CST 
//


package application.core.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the web_tictactoe package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: web_tictactoe
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SaveHighScore }
     * 
     */
    public SaveHighScore createSaveHighScore() {
        return new SaveHighScore();
    }

    /**
     * Create an instance of {@link GetTimeStampReturn }
     * 
     */
    public GetTimeStampReturn createGetTimeStampReturn() {
        return new GetTimeStampReturn();
    }

    /**
     * Create an instance of {@link GetTimeStamp }
     * 
     */
    public GetTimeStamp createGetTimeStamp() {
        return new GetTimeStamp();
    }

    /**
     * Create an instance of {@link ValidateMove }
     * 
     */
    public ValidateMove createValidateMove() {
        return new ValidateMove();
    }

    /**
     * Create an instance of {@link ValidateMoveReturn }
     * 
     */
    public ValidateMoveReturn createValidateMoveReturn() {
        return new ValidateMoveReturn();
    }

    /**
     * Create an instance of {@link GetHighScore }
     * 
     */
    public GetHighScore createGetHighScore() {
        return new GetHighScore();
    }

    /**
     * Create an instance of {@link GetHighScoreReturn }
     * 
     */
    public GetHighScoreReturn createGetHighScoreReturn() {
        return new GetHighScoreReturn();
    }

    /**
     * Create an instance of {@link SaveHighScoreReturn }
     * 
     */
    public SaveHighScoreReturn createSaveHighScoreReturn() {
        return new SaveHighScoreReturn();
    }

}
